version: "3.5"

services:
  db:
    image: postgres
    container_name: chat_db
    restart: on-failure
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5431:5432'
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - "8887:8080"
